# enviroment settings
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11

install:
  - mvn -N io.takari:maven:wrapper -Dmaven=3.6.3 -B
#  - cmd: echo %JAVA_HOME%
#  - cmd: echo %M2_HOME%

build_script:
  - mvnw install -DskipTests -B -ntp

  # verify artifacts
test_script:
  - mvnw verify -B -ntp

cache:
  - C:\Users\appveyor\.m2
